# Basic set of initial stress tests to test overcloud before running complete set of benchmarks.
browbeat:
  cloud_name: openstack
  rerun: 1
  # Two types of rerun:
  # iteration reruns on the iteration
  # complete reruns after all workloads complete
  # rerun_type: complete
  rerun_type: iteration
ansible:
  hosts: ansible/hosts
  metadata_playbook: ansible/gather/site.yml
  ssh_config: ansible/ssh-config
elasticsearch:
  enabled: false
  host: 1.1.1.1
  port: 9200
  regather: false
  metadata_files:
    - name: hardware-metadata
      file: metadata/hardware-metadata.json
    - name: environment-metadata
      file: metadata/environment-metadata.json
    - name: software-metadata
      file: metadata/software-metadata.json
    - name: version
      file: metadata/version.json
grafana:
  enabled: false
  host: example.grafana.com
  port: 3000
  dashboards:
    - openstack-general-system-performance
perfkit:
  sleep_before: 0
  sleep_after: 0
  default:
    image: centos7
    machine_type: m1.small
    os_type: rhel
    openstack_image_username: centos
    openstack_floating_ip_pool: browbeat_public
    openstack_network: browbeat_private
    timing_measurements: runtimes
    ignore_package_requirements: true
rally:
  sleep_before: 5
  sleep_after: 5
  plugins:
    - glance: rally/rally-plugins/glance
    - neutron: rally/rally-plugins/neutron
    - netcreate-boot: rally/rally-plugins/netcreate-boot
    - workloads: rally/rally-plugins/workloads
    - rally-ovs: rally/ovs/scenarios
shaker:
  server: 1.1.1.1
  port: 5555
  flavor: m1.small
  join_timeout: 600
  sleep_before: 0
  sleep_after: 0
  shaker_region: regionOne
  external_host: 2.2.2.2
yoda:
  instackenv: "/home/stack/instackenv.json"
  stackrc: "/home/stack/stackrc"

workloads:
# PerfKitBenchmarker
  - name: fio-centos-m1-small
    enabled: false
    type: perfkit
    benchmarks: fio
    openstack_volume_size: 1
# Shaker
  - name: shaker-l2
    enabled: false
    type: shaker
    density: 1
    compute: 1
    progression: linear
    time: 60
    file: lib/python2.7/site-packages/shaker/scenarios/openstack/dense_l2.yaml
  - name: shaker-l3-north-south
    enabled: false
    type: shaker
    placement: double_room
    density: 1
    compute: 1
    progression: null
    time: 60
    file: lib/python2.7/site-packages/shaker/scenarios/openstack/dense_l3_north_south.yaml
  - name: shaker-l3-east-west
    enabled: false
    type: shaker
    density: 1
    compute: 1
    time: 60
    file: lib/python2.7/site-packages/shaker/scenarios/openstack/dense_l3_east_west.yaml
# Rally
  - name: authenticate
    enabled: false
    type: rally
    concurrency:
      - 8
    times: 100
    scenarios:
      - name: authentic-keystone
        enabled: false
        file: rally/authenticate/keystone-cc.yml
      - name: authentic-neutron
        enabled: false
        file: rally/authenticate/validate_neutron-cc.yml
      - name: authentic-nova
        enabled: false
        file: rally/authenticate/validate_nova-cc.yml

  - name: cinder
    enabled: false
    type: rally
    concurrency:
      - 2
    times: 10
    scenarios:
      - name: create-attach-volume-cirros
        enabled: false
        image_name: cirros
        flavor_name: m1.tiny
        file: rally/cinder/cinder-create-and-attach-volume-cc.yml

  - name: keystonebasic
    enabled: false
    type: rally
    concurrency:
      - 8
    times: 100
    scenarios:
      - name: create-and-list-tenants
        enabled: false
        file: rally/keystonebasic/create_and_list_tenants-cc.yml
      - name: create-and-list-users
        enabled: false
        file: rally/keystonebasic/create_and_list_users-cc.yml

  - name: neutron
    enabled: false
    type: rally
    concurrency:
      - 2
    times: 10
    scenarios:
      - name: create-list-network
        enabled: false
        file: rally/neutron/neutron-create-list-network-cc.yml
      - name: create-list-port
        enabled: false
        file: rally/neutron/neutron-create-list-port-cc.yml
      - name: create-list-router
        enabled: false
        file: rally/neutron/neutron-create-list-router-cc.yml
      - name: create-list-security-group
        enabled: false
        file: rally/neutron/neutron-create-list-security-group-cc.yml
      - name: create-list-subnet
        enabled: false
        file: rally/neutron/neutron-create-list-subnet-cc.yml

  - name: nova
    enabled: false
    type: rally
    concurrency:
      - 2
    times: 10
    scenarios:
      - name: boot-snapshot-delete-cirros
        enabled: false
        file: rally/nova/nova-boot-snapshot-cc.yml
        image_name: cirros
        flavor_name: m1.xtiny
      - name: boot-list-cirros
        enabled: false
        image_name: cirros
        file: rally/nova/nova-boot-list-cc.yml
        flavor_name: m1.xtiny
      - name: boot-show-cirros
        enabled: false
        image_name: cirros
        file: rally/nova/nova-boot-show-cc.yml
        flavor_name: m1.xtiny
      - name: boot-bounce-delete-cirros
        enabled: false
        image_name: cirros
        file: rally/nova/nova-boot-bounce-delete-cc.yml
        flavor_name: m1.xtiny
      - name: boot-lock-unlock-cirros
        enabled: false
        image_name: cirros
        file: rally/nova/nova-lock-unlock-cc.yml
        flavor_name: m1.xtiny

  - name: glance
    enabled: false
    type: rally
    concurrency:
      - 2
    times: 10
    scenarios:
      - name: create-and-delete-image
        enabled: false
        image_location: /home/stack/cirros.qcow2
        container_format: bare
        disk_format: qcow2
        file: rally/glance/create-and-delete-image-cc.yml

  - name: simple-plugins
    enabled: false
    type: rally
    concurrency:
      - 8
    times: 10
    scenarios:
      - name: netcreate-boot
        enabled: false
        enable_dhcp: true
        image_name: cirros
        flavor_name: m1.tiny
        file: rally/rally-plugins/netcreate-boot/netcreate_nova_boot.yml
      - name: netcreate-boot-ping
        enabled: false
        image_name: cirros
        flavor_name: m1.xtiny
        ext_net_id:
        file: rally/rally-plugins/netcreate-boot/netcreate_nova_boot_fip_ping.yml
      - name: router-subnet-create-delete
        enabled: false
        num_networks:  5
        file: rally/rally-plugins/neutron/router_subnet_create_delete.yml
      - name: glance-create-boot-delete
        enabled: false
        image_location: /home/stack/cirros.qcow2
        flavor_name: m1.xtiny
        file: rally/rally-plugins/glance/glance_create_boot_delete.yml
      - name: neutron-securitygroup-port
        enabled: false
        file: rally/rally-plugins/neutron/securitygroup_port.yml

  - name: plugin-workloads
    enabled: false
    type: rally
    concurrency:
      - 1
    times: 1
    scenarios:
      - name: linpack
        enabled: false
        image_name: browbeat-linpack
        flavor_name: m1.small
        external_network:
        net_id:
        file: rally/rally-plugins/workloads/linpack.yml

      - name: browbeat-pbench-uperf
        enabled: false
        user: root
        image_name: browbeat-uperf
        flavor_name: m1.small
        # hypervisor_server: "nova:overcloud-compute-1.localdomain"
        # hypervisor_client: "nova:overcloud-compute-0.localdomain"
        external_network:
        net_id:
        protocols: tcp,udp
        instances: 1
        num_pairs: 1
        samples: 1
        test_types: stream,rr
        message_sizes: 64,1024,16384
        test_name: "browbeat-pbench-uperf"
        send_results: true
        cloudname:
        elastic_host:
        elastic_port: 9200
        file: rally/rally-plugins/workloads/pbench-uperf.yml

# Rally ovs
  - name: plugin-workloads
    enabled: true
    type: rally-ovs
    concurrency:
      - 1
    times: 1
    scenarios:
      - name: create_sandbox
        enabled: false
        file: create_sandbox.yml
        farm_node:
        batch: 1
        amount: 1
        tag: ToR1
        network: eth1
        start_cidr: 192.168.33.10/24
        controller: ovn-controller-node
        farm_node: ovn-farm-node-0
      - name: create-and-bind-ports
        enabled: true
        file: rally/ovs/scenarios/create-and-bind-ports.yml
        controller:
          node: "ovn-controller-node"
          cidr: "172.16.0.1/16"
          net_dev: "em1"
        farms:
          - node: "ovn-farm-node-0"
            cidr: "172.16.1.1/16"
            net_dev: "em1"
          - node: "ovn-farm-node-1"
            cidr: "172.16.2.1/16"
            net_dev: "em1"
          - node: "ovn-farm-node-2"
            cidr: "172.16.3.1/16"
            net_dev: "em1"
        sandboxes_per_farm: 24
        networks_per_cluster: 180
        ports_per_network: 2
        network_start_cidr: "10.0.0.0/8"
        concurrency:
          - 1
      - name: cleanup-sandboxes.yml
        enabled: false
        file: rally/ovs/scenarios/cleanup-sandboxes.yml
        controller:
          node: "ovn-controller-node"
          cidr: "172.16.0.1/16"
          net_dev: "em1"
